### ISSUE TITLE
Range error

### ISSUE THREAD

**Issue by lambemaaz** [dc-exe/Health_and_Doctor_Appointment#3]
I

**Comment by dc-exe** [comment]
`return ListView.builder(
            scrollDirection: Axis.vertical,
            physics: ClampingScrollPhysics(),
            shrinkWrap: true,
            itemCount: 5,`  // <--

It is because itemCount value might be out of range. You can make it dynamic by `snapshot.data.size` with size of your data.

**Comment by lambemaaz** [comment]
In which file i have to write this?

**Comment by dc-exe** [comment]
`TopRatedList.dart`

**Comment by lambemaaz** [comment]
Hello Darshak Sir,
I have been your app as my project, Iam a student, it is a great and
excellent application.
I need some changes in it. Could you please make it?

The App is Medic.ly
1] I want doctor login in it.
2] Doctors can see the patient's uploaded file like in pdf form.
3] Doctors can prescribe back to patients in pdf form or image form.



Sir it is urgent for me I would like to Offer you 2000 for this changes.It
will be great help from your side if you include this in it.

Thanks & Regards.

**Comment by databasedentapp** [comment]
How to add a doctor

**Comment by databasedentapp** [comment]
How to add a doctor

**Comment by dc-exe** [comment]
> How to add a doctor

It is connected to firebase. You have to integrate it with your firebase and doctors in firestore collection - doctor. Firestore structure is as shown in the reame.md

**Comment by dc-exe** [comment]
> can you post a screenshot of your firestore collection

![Screenshot 2021-04-09 132750](https://user-images.githubusercontent.com/64014607/117766220-da9e5400-b24c-11eb-90ac-d678aa3e8168.jpg)
![Screenshot 2021-04-09 132842](https://user-images.githubusercontent.com/64014607/117766225-dc681780-b24c-11eb-95b7-aa27bf95b48e.jpg)
![Screenshot 2021-04-09 132918](https://user-images.githubusercontent.com/64014607/117766228-dd00ae00-b24c-11eb-9f74-ec4401a29da7.jpg)
![Screenshot 2021-04-09 133045](https://user-images.githubusercontent.com/64014607/117766230-dd994480-b24c-11eb-8b37-8fb4e230a722.jpg)
